name: Test
"on":
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version:
          - 14
          - 16
          - 18
    steps:
      - uses: actions/checkout@master
      - name: Test with Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3
        with:
          cache: npm
          node-version: ${{ matrix.node_version }}
      - run: npm ci
      - run: npm run test
