name: Update
"on":
  repository_dispatch:
    types:
      - octokit/openapi release
      - octokit/types.ts release
  workflow_dispatch:
    inputs:
      version:
        description: Version of https://www.npmjs.com/package/@github/openapi
        required: true
jobs:
  update_routes:
    runs-on: ubuntu-latest
    if: >-
      github.event_name == 'workflow_dispatch' ||
      github.event.client_payload.action == 'published'
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.OCTOKIT_APP_ID }}
          private-key: ${{ secrets.OCTOKIT_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: npm
      - run: git checkout routes-update || true
      - run: npm ci
      - run: npm install @octokit/types@latest
        if: >-
          github.event_name == 'repository_dispatch' && github.event.action ==
          'octokit/types.ts release'
      - run: npm run update-endpoints
        if:  >-
          github.event_name == 'repository_dispatch' && github.event.action ==
          'octokit/openapi release'
        env:
          VERSION: ${{ github.event.client_payload.release.tag_name }}
      - run: npm run update-endpoints
        if: github.event_name == 'workflow_dispatch'
        env:
          VERSION: ${{ github.event.inputs.version }}
      - name: Create Pull Request
        uses: gr2m/create-or-update-pull-request-action@v1.x
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        with:
          title: 🚧 GitHub OpenAPI specifications changed
          body: >
            See what changed at
            https://github.com/octokit/routes/releases/latest.


            Make sure to update the commits so that the merge results in helpful
            release notes, see [Merging the Pull Request & releasing a new
            version](https://github.com/octokit/rest.js/blob/main/CONTRIBUTING.md#merging-the-pull-request--releasing-a-new-version).


            In general


            - Avoid breaking if possible

            - If there are code changes, use `fix` if a problem was resolved,
            `feat` if new endpoints / parameters were added, and
            `feat(deprecation)` if a method or parameter was deprecated.
          branch: openapi-update
          commit-message: "build: cache"
          author: Octokit Bot <33075676+octokitbot@users.noreply.github.com>
          path: scripts
      - name: Create Pull Request
        uses: gr2m/create-or-update-pull-request-action@v1.x
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        with:
          branch: openapi-update
          commit-message: WIP octokit/routes updated
          author: Octokit Bot <33075676+octokitbot@users.noreply.github.com>
